name: Run QA Checks on Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install python
      run:  uv python install ${{ matrix.python-version }}

    - name: Check Quality
      run: make qa
